/**
 * Major US locations for fleet coverage map
 * Includes major cities, ports, distribution centers, and logistics hubs
 */

export interface Location {
  id: string;
  name: string;
  city: string;
  state: string;
  type: "major-city" | "port" | "distribution-center" | "airport" | "logistics-hub";
  latitude: number;
  longitude: number;
  trucks?: number;
  description?: string;
}

export const majorLocations: Location[] = [
  // Pacific Northwest
  {
    id: "seattle-sea",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
    state: "WA",
    type: "airport",
    latitude: 47.4502,
    longitude: -122.3088,
    trucks: 4,
    description: "Major Pacific Northwest hub",
  },
  {
    id: "portland-pdx",
    name: "Portland International Airport",
    city: "Portland",
    state: "OR",
    type: "airport",
    latitude: 45.5887,
    longitude: -122.5975,
    trucks: 3,
    description: "Oregon's largest airport",
  },
  {
    id: "los-angeles-lax",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    state: "CA",
    type: "airport",
    latitude: 33.9425,
    longitude: -118.4081,
    trucks: 6,
    description: "Largest port of entry on West Coast",
  },
  {
    id: "los-angeles-port",
    name: "Port of Los Angeles",
    city: "Los Angeles",
    state: "CA",
    type: "port",
    latitude: 33.7437,
    longitude: -118.2474,
    trucks: 5,
    description: "Busiest container port in North America",
  },
  {
    id: "san-diego-san",
    name: "San Diego International Airport",
    city: "San Diego",
    state: "CA",
    type: "airport",
    latitude: 32.7337,
    longitude: -117.1933,
    trucks: 3,
    description: "Southern California logistics hub",
  },
  {
    id: "san-francisco-sfo",
    name: "San Francisco International Airport",
    city: "San Francisco",
    state: "CA",
    type: "airport",
    latitude: 37.6213,
    longitude: -122.379,
    trucks: 4,
    description: "Bay Area major hub",
  },
  {
    id: "oakland-port",
    name: "Port of Oakland",
    city: "Oakland",
    state: "CA",
    type: "port",
    latitude: 37.7213,
    longitude: -122.2724,
    trucks: 4,
    description: "Major West Coast container port",
  },
  {
    id: "las-vegas-las",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    state: "NV",
    type: "airport",
    latitude: 36.0801,
    longitude: -115.1537,
    trucks: 3,
    description: "Nevada's largest airport",
  },
  {
    id: "phoenix-phx",
    name: "Phoenix Sky Harbor International",
    city: "Phoenix",
    state: "AZ",
    type: "airport",
    latitude: 33.4484,
    longitude: -112.074,
    trucks: 4,
    description: "Arizona's largest airport",
  },
  {
    id: "denver-den",
    name: "Denver International Airport",
    city: "Denver",
    state: "CO",
    type: "airport",
    latitude: 39.8561,
    longitude: -104.6737,
    trucks: 4,
    description: "Mountain West major hub",
  },
  {
    id: "salt-lake-city-slc",
    name: "Salt Lake City International",
    city: "Salt Lake City",
    state: "UT",
    type: "airport",
    latitude: 40.7884,
    longitude: -111.8787,
    trucks: 3,
    description: "Intermountain West hub",
  },

  // Midwest
  {
    id: "chicago-ord",
    name: "Chicago O'Hare International",
    city: "Chicago",
    state: "IL",
    type: "airport",
    latitude: 41.9742,
    longitude: -87.9073,
    trucks: 6,
    description: "Major Midwest logistics hub",
  },
  {
    id: "chicago-port",
    name: "Port of Chicago",
    city: "Chicago",
    state: "IL",
    type: "port",
    latitude: 41.8781,
    longitude: -87.6298,
    trucks: 4,
    description: "Great Lakes shipping hub",
  },
  {
    id: "kansas-city-mci",
    name: "Kansas City International",
    city: "Kansas City",
    state: "MO",
    type: "airport",
    latitude: 39.2976,
    longitude: -94.7139,
    trucks: 4,
    description: "Central US distribution center",
  },
  {
    id: "dallas-dfw",
    name: "Dallas/Fort Worth International",
    city: "Dallas",
    state: "TX",
    type: "airport",
    latitude: 32.8975,
    longitude: -97.038,
    trucks: 6,
    description: "Texas major hub",
  },
  {
    id: "houston-iah",
    name: "Houston George Bush Intercontinental",
    city: "Houston",
    state: "TX",
    type: "airport",
    latitude: 29.9902,
    longitude: -95.3368,
    trucks: 5,
    description: "Gulf Coast major hub",
  },
  {
    id: "houston-port",
    name: "Port of Houston",
    city: "Houston",
    state: "TX",
    type: "port",
    latitude: 29.7589,
    longitude: -95.0196,
    trucks: 5,
    description: "Busiest US port by tonnage",
  },
  {
    id: "memphis-mem",
    name: "Memphis International Airport",
    city: "Memphis",
    state: "TN",
    type: "airport",
    latitude: 35.0424,
    longitude: -89.9768,
    trucks: 5,
    description: "FedEx hub - major logistics center",
  },
  {
    id: "atlanta-atl",
    name: "Hartsfield-Jackson Atlanta International",
    city: "Atlanta",
    state: "GA",
    type: "airport",
    latitude: 33.6407,
    longitude: -84.4277,
    trucks: 6,
    description: "World's busiest airport",
  },
  {
    id: "louisville-sdf",
    name: "Louisville International Airport",
    city: "Louisville",
    state: "KY",
    type: "airport",
    latitude: 38.1744,
    longitude: -85.7362,
    trucks: 4,
    description: "UPS hub - major logistics center",
  },
  {
    id: "indianapolis-ind",
    name: "Indianapolis International",
    city: "Indianapolis",
    state: "IN",
    type: "airport",
    latitude: 39.7173,
    longitude: -86.2944,
    trucks: 3,
    description: "Midwest distribution hub",
  },

  // Northeast
  {
    id: "new-york-jfk",
    name: "John F. Kennedy International",
    city: "New York",
    state: "NY",
    type: "airport",
    latitude: 40.6413,
    longitude: -73.7781,
    trucks: 5,
    description: "Major East Coast gateway",
  },
  {
    id: "new-york-port",
    name: "Port of New York and New Jersey",
    city: "New York",
    state: "NY",
    type: "port",
    latitude: 40.6892,
    longitude: -74.0445,
    trucks: 5,
    description: "Largest port on US East Coast",
  },
  {
    id: "boston-bos",
    name: "Boston Logan International",
    city: "Boston",
    state: "MA",
    type: "airport",
    latitude: 42.3656,
    longitude: -71.0096,
    trucks: 3,
    description: "Northeast regional hub",
  },
  {
    id: "philadelphia-phl",
    name: "Philadelphia International",
    city: "Philadelphia",
    state: "PA",
    type: "airport",
    latitude: 39.8816,
    longitude: -75.2271,
    trucks: 3,
    description: "Mid-Atlantic hub",
  },
  {
    id: "philadelphia-port",
    name: "Port of Philadelphia",
    city: "Philadelphia",
    state: "PA",
    type: "port",
    latitude: 39.9526,
    longitude: -75.1652,
    trucks: 3,
    description: "Major East Coast container port",
  },
  {
    id: "newark-ewr",
    name: "Newark Liberty International",
    city: "Newark",
    state: "NJ",
    type: "airport",
    latitude: 40.6895,
    longitude: -74.1745,
    trucks: 4,
    description: "New York metro area hub",
  },
  {
    id: "baltimore-bwi",
    name: "Baltimore/Washington International",
    city: "Baltimore",
    state: "MD",
    type: "airport",
    latitude: 39.1754,
    longitude: -76.6681,
    trucks: 3,
    description: "Mid-Atlantic major hub",
  },
  {
    id: "baltimore-port",
    name: "Port of Baltimore",
    city: "Baltimore",
    state: "MD",
    type: "port",
    latitude: 39.2904,
    longitude: -76.6122,
    trucks: 3,
    description: "Major East Coast port",
  },

  // Southeast
  {
    id: "miami-mia",
    name: "Miami International Airport",
    city: "Miami",
    state: "FL",
    type: "airport",
    latitude: 25.7959,
    longitude: -80.2871,
    trucks: 4,
    description: "Gateway to Caribbean and South America",
  },
  {
    id: "miami-port",
    name: "Port of Miami",
    city: "Miami",
    state: "FL",
    type: "port",
    latitude: 25.7617,
    longitude: -80.1918,
    trucks: 3,
    description: "Cruise and cargo port",
  },
  {
    id: "orlando-mco",
    name: "Orlando International Airport",
    city: "Orlando",
    state: "FL",
    type: "airport",
    latitude: 28.4312,
    longitude: -81.3089,
    trucks: 3,
    description: "Central Florida hub",
  },
  {
    id: "jacksonville-jax",
    name: "Jacksonville International",
    city: "Jacksonville",
    state: "FL",
    type: "airport",
    latitude: 30.4941,
    longitude: -81.6879,
    trucks: 3,
    description: "Northeast Florida hub",
  },
  {
    id: "jacksonville-port",
    name: "Port of Jacksonville",
    city: "Jacksonville",
    state: "FL",
    type: "port",
    latitude: 30.3322,
    longitude: -81.6625,
    trucks: 3,
    description: "Major Southeast container port",
  },
  {
    id: "charlotte-clt",
    name: "Charlotte Douglas International",
    city: "Charlotte",
    state: "NC",
    type: "airport",
    latitude: 35.2141,
    longitude: -80.9431,
    trucks: 4,
    description: "Southeast regional hub",
  },
  {
    id: "raleigh-rdu",
    name: "Raleigh-Durham International",
    city: "Raleigh",
    state: "NC",
    type: "airport",
    latitude: 35.8776,
    longitude: -78.7875,
    trucks: 2,
    description: "Research Triangle hub",
  },
  {
    id: "savannah-sav",
    name: "Savannah/Hilton Head International",
    city: "Savannah",
    state: "GA",
    type: "airport",
    latitude: 32.1277,
    longitude: -81.2019,
    trucks: 2,
    description: "Coastal Georgia hub",
  },
  {
    id: "savannah-port",
    name: "Port of Savannah",
    city: "Savannah",
    state: "GA",
    type: "port",
    latitude: 32.0809,
    longitude: -81.1,
    trucks: 3,
    description: "Major Southeast container port",
  },

  // Great Lakes Region
  {
    id: "detroit-dtw",
    name: "Detroit Metropolitan Airport",
    city: "Detroit",
    state: "MI",
    type: "airport",
    latitude: 42.2124,
    longitude: -83.3534,
    trucks: 3,
    description: "Great Lakes region hub",
  },
  {
    id: "cleveland-cle",
    name: "Cleveland Hopkins International",
    city: "Cleveland",
    state: "OH",
    type: "airport",
    latitude: 41.4117,
    longitude: -81.8498,
    trucks: 2,
    description: "Ohio's major hub",
  },
  {
    id: "cincinnati-cvg",
    name: "Cincinnati/Northern Kentucky International",
    city: "Cincinnati",
    state: "OH",
    type: "airport",
    latitude: 39.0474,
    longitude: -84.6612,
    trucks: 2,
    description: "Ohio Valley hub",
  },
  {
    id: "milwaukee-mke",
    name: "Milwaukee Mitchell International",
    city: "Milwaukee",
    state: "WI",
    type: "airport",
    latitude: 42.9471,
    longitude: -87.8967,
    trucks: 2,
    description: "Wisconsin's major hub",
  },

  // Mountain Region
  {
    id: "albuquerque-abq",
    name: "Albuquerque International",
    city: "Albuquerque",
    state: "NM",
    type: "airport",
    latitude: 35.0394,
    longitude: -106.6365,
    trucks: 2,
    description: "Southwest regional hub",
  },

  // Alaska & Hawaii
  {
    id: "anchorage-anc",
    name: "Ted Stevens Anchorage International",
    city: "Anchorage",
    state: "AK",
    type: "airport",
    latitude: 61.1744,
    longitude: -149.9003,
    trucks: 1,
    description: "Alaska's major hub",
  },
  {
    id: "honolulu-hnl",
    name: "Daniel K. Inouye Honolulu International",
    city: "Honolulu",
    state: "HI",
    type: "airport",
    latitude: 21.3187,
    longitude: -157.9225,
    trucks: 1,
    description: "Hawaii's major hub",
  },
];

export const getLocationsByState = (state: string): Location[] => {
  return majorLocations.filter((loc) => loc.state === state);
};

export const getLocationsByType = (type: Location["type"]): Location[] => {
  return majorLocations.filter((loc) => loc.type === type);
};

export const getTotalTrucks = (): number => {
  return majorLocations.reduce((sum, loc) => sum + (loc.trucks || 0), 0);
};
